- name: init directory and common file
  include_tasks:
    file: sub_init.yml
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - remove-logs
    - init-common
    - restore-gas-prices
    - set-gas-prices

- name: copy config files and bin files
  include_tasks:
    file: sub_copy_files.yml
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - remove-logs
    - deploy-slaves
    - only-upgrade-chain-bin
    - only-start-stopped-chain-node
    - set-fixed-deposit-rates

- name: deploy all chain nodes, include master node and slave nodes
  include_tasks:
    file: sub_deploy.yml
  tags:
    - deploy
    - redeploy
    - deploy-slaves

- name: restart all chain nodes, include master node and slave nodes
  include_tasks:
    file: sub_restart.yml
  tags:
    - restart
    - only-upgrade-chain-bin
    - fast-restart

- name: start all chain nodes, include master node and slave nodes
  include_tasks:
    file: sub_start.yml
  tags:
    - start
    - only-start-stopped-chain-node
    - fast-start

- name: stop all chain nodes, include master node and slave nodes
  include_tasks:
    file: sub_stop.yml
  tags:
    - stop

- name: remove chain logs
  shell: /bin/bash deploy.sh -t remove-logs
  when: inventory_hostname in groups[slaves_group] or groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - remove-logs

- name: auto generate validators and regions
  include_tasks:
    file: sub_gen_regions.yml
  tags:
    - gen-validator-id
    - init-region
    - remove-region
    - do-exec-init-region
    - sync-init-region-sh

- name: set or restore gas prices
  include_tasks:
    file: sub_change_gas_prices.yml
  tags:
    - set-gas-prices
    - restore-gas-prices

- name: set fixed deposit rates
  include_tasks:
    file: sub_set_fix_deposit_rates.yml
  tags:
    - set-gas-prices
    - restore-gas-prices

- name: query chain status
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: ps aux | grep {{ common.chain_bin_name }} | grep -v "grep"
  tags:
    - status

- name: kill chain
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: ps aux | grep {{ common.chain_bin_name }} | grep -v "grep" | awk '{print $2}' | xargs kill -9
  tags:
    - stop
    - kill

- name: get help hints
  shell: /bin/bash deploy.sh -help
  when: inventory_hostname in groups[slaves_group] or groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - help