- name: copy init work directory shell script file
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  copy:
    src: ../files/{{item}}
    dest: "/tmp/{{item}}"
  with_items:
    - init_work_dir.sh
  tags:
    - deploy
    - redeploy
    - init-common

- name: execute init work directory shell script
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: sh /tmp/init_work_dir.sh {{chain_deploy_home_dir}}
  tags:
    - deploy
    - redeploy
    - init-common

- name: upload common.sh file to work directory
  ansible.builtin.template:
    src: shell/common.sh.j2
    dest: "{{chain_deploy_home_dir}}/common.sh"
  when:
    - "inventory_hostname in groups[master_group] or groups[slaves_group]"
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - remove-logs
    - init-common

- name: copy main shell script files
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  copy:
    src: ../files/{{item}}
    dest: "{{chain_deploy_home_dir}}"
  with_items:
    - func.sh
    - deploy.sh
    - init.sh
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - remove-logs

- name: mkdir bin dir
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: mkdir -p bin
  args:
    chdir: "{{chain_deploy_home_dir}}"
  tags:
    - deploy
    - redeploy
    - start
    - restart

- name: copy bin files
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  copy:
    src: "{{chain_bin_file_dir}}/{{item}}"
    dest: "{{chain_deploy_home_dir}}/bin/"
  with_items:
    - "{{ common.chain_bin_name }}"
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - only-upgrade-chain-bin
    - only-start-stopped-chain-node

- name: give executable permissions to chain binary
  when: (not has_root_pwd) and (inventory_hostname in groups[master_group] or groups[slaves_group])
  shell: /bin/bash init.sh
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - only-upgrade-chain-bin
    - only-start-stopped-chain-node

- name: give executable permissions to chain binary for root user
  when: has_root_pwd and (inventory_hostname in groups[master_group] or groups[slaves_group])
  shell: chmod +x {{item}}
  become_method: sudo
  become: yes
  become_user: root
  with_items:
    - "{{ common.chain_bin_name }}"
  args:
    chdir: "{{chain_deploy_home_dir}}/bin"
  tags:
    - deploy
    - redeploy
    - start
    - restart
    - only-upgrade-chain-bin
    - only-start-stopped-chain-node

- name: deploy master
  shell: /bin/bash deploy.sh -t redeploy --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }} --admin-amount 0mec && sleep 5
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - deploy
    - redeploy

- name: start master
  shell: /bin/bash deploy.sh -t start-master --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - start
    - only-start-stopped-chain-node
    - fast-start

- name: restart master
  shell: /bin/bash deploy.sh -t restart --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - restart
    - only-upgrade-chain-bin
    - fast-restart

- name: copy master genesis file
  when: inventory_hostname in groups[master_group]
  copy :
    src: "{{chain_deploy_home_dir}}/nodes/node1/config/{{item}}"
    dest: "{{chain_deploy_home_dir}}/{{item}}"
    remote_src: yes
  with_items:
    - genesis.json
  tags:
    - deploy
    - redeploy

- name: 从主节点下载genesis.json文件到控制节点
  when: inventory_hostname in groups[master_group]
  fetch:
    src: "{{ chain_deploy_home_dir }}/genesis.json"
    dest: "/tmp/"
    flat: yes
  register: fetch_result
  tags:
    - deploy
    - redeploy

- name: 从控制节点复制genesis.json文件到从节点
  when: inventory_hostname in groups[slaves_group]
  copy:
    src: "/tmp/genesis.json"
    dest: "{{ chain_deploy_home_dir }}/genesis.json"
  tags:
    - deploy
    - redeploy

- name: get master node id
  when: inventory_hostname in groups[master_group]
  shell: ./{{ common.chain_bin_name }} tendermint show-node-id --home {{chain_deploy_home_dir}}/nodes/node1
  register: masterNodeIdResult
  args:
    chdir: "{{chain_deploy_home_dir}}/bin"
  tags:
    - deploy
    - redeploy

- name: debug get master node id result
  debug:
    var: masterNodeIdResult
  tags:
    - deploy
    - redeploy

- name: save master node id to file
  when: inventory_hostname in groups[master_group]
  copy:
    content: "{{ masterNodeIdResult.stdout | b64decode }}"
    dest: "{{chain_deploy_home_dir}}/nodeId.txt"
  tags:
    - deploy
    - redeploy

- name: 从主节点下载node id文件到控制节点
  when: inventory_hostname in groups[master_group]
  fetch:
    src: "{{ chain_deploy_home_dir }}/nodeId.txt"
    dest: "/tmp/"
    flat: yes
  register: fetch_result
  tags:
    - deploy
    - redeploy

- name: 从控制节点复制node id文件到从节点
  when: inventory_hostname in groups[slaves_group]
  copy:
    src: "/tmp/nodeId.txt"
    dest: "{{ chain_deploy_home_dir }}/nodeId.txt"
  tags:
    - deploy
    - redeploy

- name: retrieve master node id from file
  when: inventory_hostname in groups[slaves_group]
  slurp:
    src: "{{chain_deploy_home_dir}}/nodeId.txt"
  register: master_node_id_result
  tags:
    - deploy
    - redeploy

- name: debug master_node_id_result
  debug:
    var: master_node_id_result
  tags:
    - deploy
    - redeploy

- name: deploy slaves
  shell: /bin/bash deploy.sh -t redeploy-slaves --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }} --master-node-id "{{ master_node_id_result.content }}" --master-node-ip "{{ master_node_host_ip }}"
  when: inventory_hostname in groups[slaves_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - deploy
    - redeploy

- name: start slaves
  shell: /bin/bash deploy.sh -t start-slaves --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }} --master-node-id "{{ master_node_id_result.content }}"
  when: inventory_hostname in groups[slaves_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - start
    - only-start-stopped-chain-node
    - fast-start

- name: restart slaves
  shell: /bin/bash deploy.sh -t restart-slaves --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[slaves_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - restart
    - only-upgrade-chain-bin
    - fast-restart

- name: query chain status
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: ps aux | grep {{ common.chain_bin_name }} | grep -v "grep"
  tags:
    - status

- name: kill chain
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: ps aux | grep {{ common.chain_bin_name }} | grep -v "grep" | awk '{print $2}' | xargs kill -9
  tags:
    - stop
    - kill

- name: copy get validator shell script file
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  copy:
    src: ../files/{{item}}
    dest: "{{chain_deploy_home_dir}}"
  with_items:
    - get-validator-id.sh
  tags:
    - init-region
    - remove-region

- name: get all validator id, save them to tmp dir
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  shell: /bin/bash get-validator-id.sh --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  register: adminAddrResult
  args:
    chdir: "{{chain_deploy_home_dir}}/"
    executable: /bin/bash
  tags:
    - init-region
    - remove-region
    - gen-validator-id

- name: 下载目录/tmp/validator-pub-keys
  when: inventory_hostname in groups[master_group] or groups[slaves_group]
  synchronize:
    src: "/tmp/validator-pub-keys"
    dest: "/tmp/"
    mode: pull
  tags:
    - init-region
    - remove-region

- name: copy all /tmp/validator-pub-keys directory to master node
  when: inventory_hostname in groups[master_group]
  copy:
    src: /tmp/{{item}}
    dest: "{{chain_deploy_home_dir}}/"
  with_items:
    - validator-pub-keys
  tags:
    - init-region
    - remove-region

- name: copy init region shell related script files
  when: inventory_hostname in groups[master_group]
  copy:
    src: ../files/{{item}}
    dest: "{{chain_deploy_home_dir}}"
  with_items:
    - func.sh
    - common.sh
    - init_region.sh
  tags:
    - init-region
    - remove-region
    - do-exec-init-region
    - sync-init-region-sh

- name: execute init region operation
  shell: chmod +x init_region.sh && /bin/bash init_region.sh -t create --begin-pos {{ validator_begin_node_pos }} --end-pos {{ validator_end_node_pos }}
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - init-region
    - remove-region
    - do-exec-init-region

- name: test init region
  shell: curRegions={{regions[hostvars[inventory_hostname]['index']]['list']}} && echo "$curRegions"
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
  tags:
    - test

- name: remove chain logs
  shell: /bin/bash deploy.sh -t remove-logs
  when: inventory_hostname in groups[slaves_group] or groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - remove-logs

- name: set fixed deposit rates
  shell: /bin/bash deploy.sh -t set-fixed-deposit-rates
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - set-fixed-deposit-rates

- name: restore the minimum gas prices in both the master node and all the slave nodes for the master host
  shell: /bin/bash deploy.sh -t restore-master-gas-prices --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - restore-gas-prices

- name: set the minimum gas prices in both the master node and all the slave nodes for the master host
  shell: /bin/bash deploy.sh -t set-master-gas-prices --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[master_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - set-gas-prices

- name: restore the minimum gas prices in all the slave nodes for the slave host
  shell: /bin/bash deploy.sh -t restore-slaves-gas-prices --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[slaves_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - restore-gas-prices

- name: set the minimum gas prices in all the slave nodes for the slave host
  shell: /bin/bash deploy.sh -t set-slaves-gas-prices --begin-pos {{ hostvars[inventory_hostname]['begin_pos'] }} --end-pos {{ hostvars[inventory_hostname]['end_pos'] }}
  when: inventory_hostname in groups[slaves_group]
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - set-gas-prices

