- name: upload crontab.sh
  ansible.builtin.template:
    src: shell/crontab.sh.j2
    dest: "{{chain_deploy_home_dir}}/crontab.sh"
  when:
    - "inventory_hostname in groups[master_group] or groups[slaves_group]"
  tags:
    - cron

- name: execute crontab.sh
  become_method: sudo
  become: yes
  become_user: root
  shell: /bin/bash crontab.sh
  when:
    - "inventory_hostname in groups[master_group] or groups[slaves_group]"
  args:
    chdir: "{{chain_deploy_home_dir}}"
    executable: /bin/bash
  tags:
    - cron
